name: CI

on:
  workflow_call:
  push:
    paths-ignore:
      - ".github/**"
      - "**/README*"
    branches-ignore:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        uses: actions/cache@v3
        id: cache_dependencies
        env:
          cache-name: cache
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('yarn.lock') }}
      - run: yarn --frozen-lockfile --non-interactive

      - name: Run lint
        run: yarn run lint
